# Generated by Django 4.1.1 on 2022-09-12 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_category_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.BooleanField()),
                ('date_marker', models.DateTimeField(auto_now_add=True, verbose_name='Дата ознакомления')),
                ('comment', models.TextField(blank=True, verbose_name='Примечание')),
                ('id_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
